language: python
python:
- 2.7
install:
- pip install -r requirements.txt
- wget http://security.ubuntu.com/ubuntu/pool/main/libs/libssh/libssh-4_0.5.2-1ubuntu0.12.04.4_amd64.deb
- wget http://us.archive.ubuntu.com/ubuntu/pool/main/u/udev/libgudev-1.0-0_175-0ubuntu9.9_amd64.deb
- sudo dpkg -i libssh-4_0.5.2-1ubuntu0.12.04.4_amd64.deb
- sudo dpkg -i libgudev-1.0-0_175-0ubuntu9.9_amd64.deb
- sudo apt-get install -f -m texlive-full
script:
- make all
env:
  global:
  - secure: bdR0He27Xv2uPww5rP4QwMg1yo2qI9iLkObVNI6v1cd/BLmE/mr957dp5wHwBnMNrpeZtn0eNzrJQw9qV2f0g7Gua0DdXLzLEMzRqoCIQhT39vbUU0JiwVJTkk4cYe4NdghUEFAQcL2NOT6sqJulMmiVmCjALw2be8VoeGN87H4=
before_install:
- git submodule update --init --recursive
after_success: 
- bash deploy.sh
