language: python
python:
- 2.7
addons:
  apt:
    packages:
    - texlive-full
    - texlive-xetex
    - gs-cjk-resource
install:
- pip install -r requirements.txt
- sudo apt-get install -y latex-cjk-all
script:
- make all
env:
  global:
  - secure: bdR0He27Xv2uPww5rP4QwMg1yo2qI9iLkObVNI6v1cd/BLmE/mr957dp5wHwBnMNrpeZtn0eNzrJQw9qV2f0g7Gua0DdXLzLEMzRqoCIQhT39vbUU0JiwVJTkk4cYe4NdghUEFAQcL2NOT6sqJulMmiVmCjALw2be8VoeGN87H4=
before_install:
- git submodule update --init --recursive
after_success: 
- bash deploy.sh
